// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xndcuwcgzjvtvixlxlfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZGN1d2Nnemp2dHZpeGx4bGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjYzODYsImV4cCI6MjA2ODcwMjM4Nn0.MWCxtcmIaNKeUyuY5RSnvsQLa9gfIVph7CqkiYWkk-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});